### PR TITLE
move (& rename) the c14n challenges section to an appendix

### PR DESCRIPTION
**Pull request by bc-pi**
Rename and move the c14n section to an appendix. Also add a paragraph attempting to provide a bit more context in the new location. 

for #175

### CODE REVIEW

**Review by Sakurann — APPROVED** [review]
I wasn't totally sure about the title "Disclosure Format Considerations", but can't think of a better one and after re-reading the content, I think it captures the goal.

**Comment by bc-pi** [comment]
I'm not thrilled with the section name either but thought "The Challenge of Canonicalization" felt really out of place in an appendix so wanted to change it. "Disclosure Format Considerations" was the best I could come up with.

**Comment by danielfett** [comment]
Looks good to me, but we should probably reference the new appendix somewhere in the main body.

**Comment by bc-pi** [comment]
> Looks good to me, but we should probably reference the new appendix somewhere in the main body.

Please add such a reference wherever you think is appropriate.

**Comment by bc-pi** [comment]
> Looks good to me, but we should probably reference the new appendix somewhere in the main body. 

went ahead and did that with 0db6e9865fedf8437e75b9f2eb9d12fc52ee48f1

**Comment by danielfett** [comment]
Thank you!

**Pull request merged**
