### PR TITLE
 WGLC updates 2/x (remove sentence in intro)

### PR DESCRIPTION
**Pull request by bc-pi**
remove repetitive repetitive sentence per Dick https://mailarchive.ie)tf.org/arch/msg/oauth/brjnGB53MApGNCsXC03ungeWxI4/

### CODE REVIEW

**Review by danielfett — APPROVED** [review]
Merci!

**Review by Sakurann — CHANGES_REQUESTED** [review]
I am ok with adding Dick as a contributor, but I am not ok removing this sentence (line 111), sorry. like, this is the only sentence that is left from when we used to say "sd-jwt can be used with json-ld", and "The JSON-based representation of claims in a signed JWT..." in the intro is not as clear as the sentence being deleted.

**Comment by bc-pi** [comment]
> I am ok with adding Dick as a contributor, but I am not ok removing this sentence (line 111), sorry. like, this is the only sentence that is left from when we used to say "sd-jwt can be used with json-ld", and "The JSON-based representation of claims in a signed JWT..." in the intro is not as clear as the sentence being deleted.

Okay, let's just close this one then.

**Comment by bc-pi** [comment]
@danielfett is going to rework the introduction too

**Pull request closed without merging**
