### PR TITLE
use the term Key Binding rather than Holder Binding

### PR DESCRIPTION
**Pull request by bc-pi**
Change to use Key Binding and Key Binding JWT rather than Holder Binding and Holder Binding JWT. 

for issue #281

### CODE REVIEW

**Comment by bc-pi** [comment]
Did some more work on this based on discussions yesterday and I believe it's now ready for review @Sakurann and @danielfett

**Comment by bc-pi** [comment]
Editor's copy for this branch: https://drafts.oauth.net/oauth-selective-disclosure-jwt/bc/key-rather-than-holder/draft-ietf-oauth-selective-disclosure-jwt.html

**Comment by bc-pi** [comment]
I realized/noticed that there were still things like `holder_binding` in yaml and `hb_` in file names.  So I changed `holder_binding` to `key_binding` and `hb_` to `kb_` and `holder binding` to `key binding` throughout the sd-jwt lib to try and have code, comments, and generated files reflect calling it key binding rather than holder binding. And made the corresponding changes here.

**Review by Sakurann — APPROVED** [review]
Thanks Brian, this looks good. I believe this is the right direction.

**Review by danielfett — APPROVED** [review]

**Pull request merged**
