### PR TITLE
Fix Issue #256 - Example 2a

### PR DESCRIPTION
**Pull request by danielfett**

### CODE REVIEW

**Comment by bc-pi** [comment]
The changes to [sd_jwt/examples/simple_structured.yml](https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/257/files#diff-419b00ae17c9bf1fc5862b7cb23eb2c0b44423b8422ccda8fcf4df73b7cef7a6) look right but the files in simple_structured/ didn't get updated (or looks like updated https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/257/commits/82763136eacecbfa0ce0d2446c2a0d7f06aa31d2#diff-831dca81705d15f42d1f30e0228a989a66a1dcb9695fc3e36804f3654a4b81db and then reverted https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/257/commits/11651b10fdae7d69a43bfca3c1a38760d5f55c3b#diff-831dca81705d15f42d1f30e0228a989a66a1dcb9695fc3e36804f3654a4b81db).  

I'm having a hard time following the changes :( 
 but the editors copy of the PR branch doesn't have the update https://drafts.oauth.net/oauth-selective-disclosure-jwt/danielfett/fix-example/draft-ietf-oauth-selective-disclosure-jwt.html#name-example-2a-handling-structu

**Comment by danielfett** [comment]
This time I removed all changed output files to not cause merge conflicts with the other PRs we have. 

It seems like we should switch to generating the examples in github actions and not committing them.

**Comment by bc-pi** [comment]
> This time I removed all changed output files to not cause merge conflicts with the other PRs we have.

Ok, that's sort of what I suspected.

> It seems like we should switch to generating the examples in github actions and not committing them.

Maybe...

**Review by bc-pi — APPROVED** [review]

**Review by Sakurann — APPROVED** [review]

**Comment by Sakurann** [comment]
(trusting it will be merged to minimize conflicting changes with other PRs)

**Pull request merged**
